"""Static reference table of real, publicly documented rocket engine specs.

Thrust/Isp/propellant are physical constants — no free live API publishes them
reliably at per-engine granularity, so this is intentionally a small static
table rather than an API call. Values are widely cited public figures (order of
magnitude/approximate for older vehicles); joined to live launch data on
`rocket_family`.
"""

ENGINE_SPECS = [
    {
        "rocket_family": "Falcon 9",
        "engine_name": "Merlin 1D",
        "manufacturer": "SpaceX",
        "engine_count": 9,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 845,
        "thrust_vac_kN": 914,
        "isp_sl_s": 282,
        "isp_vac_s": 311,
    },
    {
        "rocket_family": "Falcon Heavy",
        "engine_name": "Merlin 1D",
        "manufacturer": "SpaceX",
        "engine_count": 27,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 845,
        "thrust_vac_kN": 914,
        "isp_sl_s": 282,
        "isp_vac_s": 311,
    },
    {
        "rocket_family": "Saturn V",
        "engine_name": "Rocketdyne F-1",
        "manufacturer": "Rocketdyne",
        "engine_count": 5,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 6770,
        "thrust_vac_kN": 7770,
        "isp_sl_s": 263,
        "isp_vac_s": 304,
    },
    {
        "rocket_family": "Space Shuttle",
        "engine_name": "RS-25 (SSME)",
        "manufacturer": "Rocketdyne",
        "engine_count": 3,
        "propellant_type": "LOX/LH2",
        "thrust_sl_kN": 1860,
        "thrust_vac_kN": 2279,
        "isp_sl_s": 366,
        "isp_vac_s": 452,
    },
    {
        "rocket_family": "Soyuz",
        "engine_name": "RD-108A",
        "manufacturer": "NPO Energomash",
        "engine_count": 1,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 839,
        "thrust_vac_kN": 990,
        "isp_sl_s": 257,
        "isp_vac_s": 320,
    },
    {
        "rocket_family": "Atlas V",
        "engine_name": "RD-180",
        "manufacturer": "NPO Energomash",
        "engine_count": 1,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 3830,
        "thrust_vac_kN": 4152,
        "isp_sl_s": 311,
        "isp_vac_s": 338,
    },
    {
        "rocket_family": "Delta IV Heavy",
        "engine_name": "RS-68A",
        "manufacturer": "Aerojet Rocketdyne",
        "engine_count": 3,
        "propellant_type": "LOX/LH2",
        "thrust_sl_kN": 3137,
        "thrust_vac_kN": 3560,
        "isp_sl_s": 365,
        "isp_vac_s": 412,
    },
    {
        "rocket_family": "Ariane 5",
        "engine_name": "Vulcain 2",
        "manufacturer": "ArianeGroup",
        "engine_count": 1,
        "propellant_type": "LOX/LH2",
        "thrust_sl_kN": 960,
        "thrust_vac_kN": 1390,
        "isp_sl_s": 318,
        "isp_vac_s": 431,
    },
    {
        "rocket_family": "Electron",
        "engine_name": "Rutherford",
        "manufacturer": "Rocket Lab",
        "engine_count": 9,
        "propellant_type": "LOX/RP-1",
        "thrust_sl_kN": 22.7,
        "thrust_vac_kN": 25.8,
        "isp_sl_s": 303,
        "isp_vac_s": 311,
    },
    {
        "rocket_family": "New Glenn",
        "engine_name": "BE-4",
        "manufacturer": "Blue Origin",
        "engine_count": 7,
        "propellant_type": "LOX/LNG",
        "thrust_sl_kN": 2400,
        "thrust_vac_kN": 2500,
        "isp_sl_s": 292,
        "isp_vac_s": 310,
    },
]
